name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: echo node version
  #       run: node --version

  #     - name: Checkout code
  #       uses: actions/checkout@v4.1.1

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Run tests
  #       run: npm test

  format:
    runs-on: ubuntu-latest
    permissions: # Job-level permissions configuration starts here
      contents: write # 'write' access to repository contents
      pull-requests: write # 'write' access to pull requests

    steps:
      - name: echo Github Event Name
        run: |
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "${{ toJson(github.event) }}" | jq

      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: npm ci

      - name: Run format
        run: npm run format

      - name: Commit Formatted Files
        run: |
          git config --local user.email "MohamedTahaaAmer@gmail.com"
          git config --local user.name "MohamedTahaAmer"
          git add .
          git commit -m "Format code"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
